name: OreGenReloaded
main: com.twanl.oregenreloaded.OreGenReloaded
version: 1.3.0
author: Twan

commands:
  og:
    description: Shows list of commands.

permissions:
  og.reload:
    description: Reloads the config file.
    default: false